version: "3.8"
services:
  frontend:
    build: ./frontend/
    ports:
      - 6900:6900
      - 8080:8080
    container_name: wall-frontend
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./backend/data-db:/data/db
      - ./mongo-entry.js:/docker-entrypoint-initdb.d/mongo-entry.js
    environment:
      MONGO_INITDB_DATABASE: wall
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - "mongodb"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: "mongodb"
  backend:
    build: ./backend/
    ports:
      - 7000:7000
      - 9230:9230
    depends_on:
      - "mongodb"
      - "mongo-express"
    container_name: wall-backend
    volumes:
      - ./backend/:/app/
      - /app/node_modules
  minio:
    image: minio/minio:latest
    expose:
      - 9000
      - 9001
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-admin
    volumes:
      - ./backend/minio:/data
  mc:
    image: minio/mc
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio-admin;
      /usr/bin/mc policy set public myminio/thumbnails;
      /usr/bin/mc policy set public myminio/avatar;
      exit 0;
      "
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio
